import sqlite3

def delete_failed_sources():
    with sqlite3.connect('airfare_index.db') as conn:
        cursor = conn.cursor()
        
        # Deletes all records generated by the experimental scrapers
        cursor.execute("""
            DELETE FROM raw_fares 
            WHERE ota_source IN ('Air India Express Direct', 'Ixigo')
        """)
        
        deleted_count = cursor.rowcount
        conn.commit()
        
    print(f"✅ Successfully deleted {deleted_count} records from Air India Express and Ixigo.")

if __name__ == "__main__":
    delete_failed_sources()